# syntax=docker/DockerFile:1

FROM python:3.8-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY . .
ENTRYPOINT [ "python"]
CMD ["app.py"]
#CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]